---
type: cloudgenix template
version: 1.0
# Created at 2021-05-16T17:53:47.109280Z
# by system_2751@soumyars2.com
sites v4.5:
  BLR-Branch:
    address:
      city: Bengaluru
      country: India
      post_code:
      state: Karnataka
      street: '41'
      street2:
    admin_state: active
    description: Test description 0510
    element_cluster_role: SPOKE
    elements v2.4:
      BLR-Branch-Device:
        admin_action:
        admin_renew_state:
        allowed_roles:
        - HUB
        - SPOKE
        application_probe v2.0:
          description:
          enable_probe: true
          name: default-probe-configuration-16161568593970255
          source_interface_id:
          tags:
        cluster_insertion_mode:
        cluster_member_id:
        connected: true
        deployment_op:
        description:
        element_security_zones v2.0: []
        interfaces v4.10:
          '1':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description:
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipfixcollectorcontext_id:
            ipfixfiltercontext_id:
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            secondary_ip_configs:
            service_link_config:
            site_wan_interface_ids:
            static_arp_configs:
            sub_interface:
            tags:
            type: port
            used_for: none
          '2':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description:
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipfixcollectorcontext_id:
            ipfixfiltercontext_id:
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            secondary_ip_configs:
            service_link_config:
            site_wan_interface_ids:
            static_arp_configs:
            sub_interface:
            tags:
            type: port
            used_for: none
          '3':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipfixcollectorcontext_id:
            ipfixfiltercontext_id:
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            secondary_ip_configs:
            service_link_config:
            site_wan_interface_ids:
            static_arp_configs:
            sub_interface:
            tags:
            type: port
            used_for: none
          '4':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipfixcollectorcontext_id:
            ipfixfiltercontext_id:
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            secondary_ip_configs:
            service_link_config:
            site_wan_interface_ids:
            static_arp_configs:
            sub_interface:
            tags:
            type: port
            used_for: none
          '5':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipfixcollectorcontext_id:
            ipfixfiltercontext_id:
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            secondary_ip_configs:
            service_link_config:
            site_wan_interface_ids:
            static_arp_configs:
            sub_interface:
            tags:
            type: port
            used_for: none
          '6':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipfixcollectorcontext_id:
            ipfixfiltercontext_id:
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            secondary_ip_configs:
            service_link_config:
            site_wan_interface_ids:
            static_arp_configs:
            sub_interface:
            tags:
            type: port
            used_for: none
          '7':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipfixcollectorcontext_id:
            ipfixfiltercontext_id:
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            secondary_ip_configs:
            service_link_config:
            site_wan_interface_ids:
            static_arp_configs:
            sub_interface:
            tags:
            type: port
            used_for: none
          '8':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipfixcollectorcontext_id:
            ipfixfiltercontext_id:
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            secondary_ip_configs:
            service_link_config:
            site_wan_interface_ids:
            static_arp_configs:
            sub_interface:
            tags:
            type: port
            used_for: none
          controller 1:
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipfixcollectorcontext_id:
            ipfixfiltercontext_id:
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            secondary_ip_configs:
            service_link_config:
            site_wan_interface_ids:
            static_arp_configs:
            sub_interface:
            tags:
            type: port
            used_for: none
        l3_direct_private_wan_forwarding: true
        l3_lan_forwarding: true
        model_name: ion 3102v
        nat_policysetstack_id:
        network_policysetstack_id:
        ntp v2.0:
        - description: Default NTP template created by super user.
          name: default
          ntp_servers:
          - host: 0.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: 1.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: 2.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: 3.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: time.nist.gov
            max_poll: 15
            min_poll: 13
            version: 4
          source_interface_ids:
          tags:
        priority_policysetstack_id:
        role: SPOKE
        routing:
          bgp:
            global_config v2.2:
              admin_distance: 20
              adv_interval: 1
              graceful_restart: false
              hold_time: 90
              keepalive_time: 30
              local_as_num:
              maximum_paths: 1
              md5_secret:
              multi_hop_limit: 1
              peer_auth_type: none
              peer_retry_time: 120
              prefix_adv_type:
              prefix_adv_type_to_lan: default
              prefixes_to_adv_to_wan:
              router_id:
              stalepath_time: 120
          static v2.1: {}
        serial_number: 0cab1542-2f6a-6b0a-7998-270975d24fdc
        software_version: 5.4.7-b1
        spoke_ha_config:
        state: bound
        tags:
        tenant_id: '2751'
        toolkit v2.2:
          account_disable_interval: 5
          inactive_interval: 15
          otpkey_version: 1
          retry_login_count: 5
          ssh_enabled: true
          ssh_outbound_enabled: false
        vpn_to_vpn_forwarding: false
    extended_tags:
    location:
      description:
      latitude: 12.96991
      longitude: 77.59796
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
    waninterfaces v2.6:
      Circuit to Airtel:
        bfd_mode: aggressive
        bw_config_mode: manual
        bwc_enabled: true
        cost: 128
        description:
        label_id: Leased-Line
        link_bw_down: 30.0
        link_bw_up: 10.0
        lqm_config:
        lqm_enabled: true
        network_id: Airtel
        network_type: privatewan
        tags:
        type: privatewan
        use_for_application_reachability_probes:
        use_for_controller_connections:
        vpnlink_configuration:
      Circuit to T-MOBILE:
        bfd_mode: aggressive
        bw_config_mode: manual
        bwc_enabled: true
        cost: 128
        description:
        label_id: Internet Cable
        link_bw_down: 30.0
        link_bw_up: 10.0
        lqm_config:
        lqm_enabled: true
        network_id: T-MOBILE
        network_type: publicwan
        tags:
        type: publicwan
        use_for_application_reachability_probes:
        use_for_controller_connections:
        vpnlink_configuration:
